# Generated by Django 2.2 on 2019-05-16 00:08

import criterios.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('idCSV', models.AutoField(primary_key=True, serialize=False)),
                ('nombreArchivo', models.CharField(max_length=50)),
                ('eliminados1', models.IntegerField(default=0)),
                ('eliminados2', models.IntegerField(default=0)),
                ('eliminados3', models.IntegerField(default=0)),
                ('eliminados4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('instituto', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('idFormulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreFormulario', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('ponderado', models.CharField(blank=True, max_length=5, null=True)),
                ('condiciones', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('idCriterio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('children', models.IntegerField(default=0)),
                ('porcentaje', models.IntegerField(default=1, validators=[criterios.models.MaxValueValidator, criterios.models.MinValueValidator])),
                ('nivel', models.IntegerField(default=0)),
                ('multipleOptions', models.BooleanField(default=False)),
                ('idCriterioPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.Criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('idCondicion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('porcentaje', models.IntegerField(default=1, validators=[criterios.models.MaxValueValidator, criterios.models.MinValueValidator])),
                ('isSelected', models.BooleanField(default=False)),
                ('ponderado', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('idCriterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterios.Criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('casco', models.CharField(max_length=50)),
                ('regimen', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('csv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.CSV')),
            ],
        ),
    ]
