# Generated by Django 2.2 on 2019-04-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(max_length=50)),
                ('eliminados1', models.IntegerField(default=0)),
                ('eliminados2', models.IntegerField(default=0)),
                ('eliminados3', models.IntegerField(default=0)),
                ('eliminados4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50)),
                ('casco', models.CharField(max_length=50)),
                ('regimen', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('eslora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criterios.Usuario')),
            ],
        ),
    ]
