# Generated by Django 2.2 on 2019-05-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='condiciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
